mutation InsertUser($email: String, $name: String) {
  user: addUser(
    object: {email: $email, name: $name},
    on_conflict: {constraint: users_email_key, update_columns: name}
  ) {
    id
    email
    name
    finishedAt: finished_at
  }
}

mutation FinishQuiz($id: uuid!, $finishedAt: timestamptz!) {
  user: updateUser(
    pk_columns: {id: $id},
    _set: {finished_at: $finishedAt}
  ) {
    id
    email
    name
    finishedAt: finished_at
  }
}
